name: primitives_ffi
version: 0.0.1
description: >-
  A super simple example of encrypting a message via C code from Dart with FFI
environment:
  sdk: '>=2.19.0 <3.0.0' # Updated SDK constraint
dependencies:
  ffi: ^2.0.1 # Updated ffi version
dev_dependencies:
  test: ^1.21.0 # Updated test version
dependency_overrides:
  analyzer: 0.39.1
